#1
print ("как тебя зовут?")
name= input()
print (f"Привет {name}" )
#4
Last_name=input ('Фамилия  ')
Name = input('Ваше имя  ')
age = input('Ваш возраст  ')
work = input ('Место работы  ')
print('-----------------')
print ('---ваша карточка--- ')
print('-----------------')
print (f'Фамилия {Last_name}\nИмя {Name}\nвозраст {age}\nместо работы {work}')
print('-----------------')
# 3
matem = input ('Оценка по математике = ')
engl = input ('Оценка по английскому = ')
russ = input ('Оценка по русскому языку = ')
print('-----------------')
print (f'математика {matem} английский {engl} русский {russ}')